// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: endpoints.proto

package epservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for endpoint information
type EndpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointRequest) Reset() {
	*x = EndpointRequest{}
	mi := &file_endpoints_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointRequest) ProtoMessage() {}

func (x *EndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointRequest.ProtoReflect.Descriptor instead.
func (*EndpointRequest) Descriptor() ([]byte, []int) {
	return file_endpoints_proto_rawDescGZIP(), []int{0}
}

// Response containing all endpoint information
type EndpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Endpoints     []*Endpoint            `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointResponse) Reset() {
	*x = EndpointResponse{}
	mi := &file_endpoints_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointResponse) ProtoMessage() {}

func (x *EndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointResponse.ProtoReflect.Descriptor instead.
func (*EndpointResponse) Descriptor() ([]byte, []int) {
	return file_endpoints_proto_rawDescGZIP(), []int{1}
}

func (x *EndpointResponse) GetEndpoints() []*Endpoint {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

// Endpoint information
type Endpoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            []byte                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Endpoint) Reset() {
	*x = Endpoint{}
	mi := &file_endpoints_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Endpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Endpoint) ProtoMessage() {}

func (x *Endpoint) ProtoReflect() protoreflect.Message {
	mi := &file_endpoints_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Endpoint.ProtoReflect.Descriptor instead.
func (*Endpoint) Descriptor() ([]byte, []int) {
	return file_endpoints_proto_rawDescGZIP(), []int{2}
}

func (x *Endpoint) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *Endpoint) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

var File_endpoints_proto protoreflect.FileDescriptor

const file_endpoints_proto_rawDesc = "" +
	"\n" +
	"\x0fendpoints.proto\x12\tepservice\"\x11\n" +
	"\x0fEndpointRequest\"E\n" +
	"\x10EndpointResponse\x121\n" +
	"\tendpoints\x18\x01 \x03(\v2\x13.epservice.EndpointR\tendpoints\".\n" +
	"\bEndpoint\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\fR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port2Z\n" +
	"\x0fEndpointService\x12G\n" +
	"\fGetEndpoints\x12\x1a.epservice.EndpointRequest\x1a\x1b.epservice.EndpointResponseB+Z)github.com/bajacc/tinescale/pkg/epserviceb\x06proto3"

var (
	file_endpoints_proto_rawDescOnce sync.Once
	file_endpoints_proto_rawDescData []byte
)

func file_endpoints_proto_rawDescGZIP() []byte {
	file_endpoints_proto_rawDescOnce.Do(func() {
		file_endpoints_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_endpoints_proto_rawDesc), len(file_endpoints_proto_rawDesc)))
	})
	return file_endpoints_proto_rawDescData
}

var file_endpoints_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_endpoints_proto_goTypes = []any{
	(*EndpointRequest)(nil),  // 0: epservice.EndpointRequest
	(*EndpointResponse)(nil), // 1: epservice.EndpointResponse
	(*Endpoint)(nil),         // 2: epservice.Endpoint
}
var file_endpoints_proto_depIdxs = []int32{
	2, // 0: epservice.EndpointResponse.endpoints:type_name -> epservice.Endpoint
	0, // 1: epservice.EndpointService.GetEndpoints:input_type -> epservice.EndpointRequest
	1, // 2: epservice.EndpointService.GetEndpoints:output_type -> epservice.EndpointResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_endpoints_proto_init() }
func file_endpoints_proto_init() {
	if File_endpoints_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_endpoints_proto_rawDesc), len(file_endpoints_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_endpoints_proto_goTypes,
		DependencyIndexes: file_endpoints_proto_depIdxs,
		MessageInfos:      file_endpoints_proto_msgTypes,
	}.Build()
	File_endpoints_proto = out.File
	file_endpoints_proto_goTypes = nil
	file_endpoints_proto_depIdxs = nil
}
