// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.32.0
// source: securemsg.proto

package securemsg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageWrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to MessageType:
	//
	//	*MessageWrapper_EndpointRequest
	//	*MessageWrapper_EndpointResponse
	//	*MessageWrapper_ToRelay
	//	*MessageWrapper_FromRelay
	//	*MessageWrapper_PingMessage
	//	*MessageWrapper_PongMessage
	MessageType   isMessageWrapper_MessageType `protobuf_oneof:"message_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageWrapper) Reset() {
	*x = MessageWrapper{}
	mi := &file_securemsg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWrapper) ProtoMessage() {}

func (x *MessageWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_securemsg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWrapper.ProtoReflect.Descriptor instead.
func (*MessageWrapper) Descriptor() ([]byte, []int) {
	return file_securemsg_proto_rawDescGZIP(), []int{0}
}

func (x *MessageWrapper) GetMessageType() isMessageWrapper_MessageType {
	if x != nil {
		return x.MessageType
	}
	return nil
}

func (x *MessageWrapper) GetEndpointRequest() *EndpointRequest {
	if x != nil {
		if x, ok := x.MessageType.(*MessageWrapper_EndpointRequest); ok {
			return x.EndpointRequest
		}
	}
	return nil
}

func (x *MessageWrapper) GetEndpointResponse() *EndpointResponse {
	if x != nil {
		if x, ok := x.MessageType.(*MessageWrapper_EndpointResponse); ok {
			return x.EndpointResponse
		}
	}
	return nil
}

func (x *MessageWrapper) GetToRelay() *ToRelayMessage {
	if x != nil {
		if x, ok := x.MessageType.(*MessageWrapper_ToRelay); ok {
			return x.ToRelay
		}
	}
	return nil
}

func (x *MessageWrapper) GetFromRelay() *FromRelayMessage {
	if x != nil {
		if x, ok := x.MessageType.(*MessageWrapper_FromRelay); ok {
			return x.FromRelay
		}
	}
	return nil
}

func (x *MessageWrapper) GetPingMessage() *PingMessage {
	if x != nil {
		if x, ok := x.MessageType.(*MessageWrapper_PingMessage); ok {
			return x.PingMessage
		}
	}
	return nil
}

func (x *MessageWrapper) GetPongMessage() *PongMessage {
	if x != nil {
		if x, ok := x.MessageType.(*MessageWrapper_PongMessage); ok {
			return x.PongMessage
		}
	}
	return nil
}

type isMessageWrapper_MessageType interface {
	isMessageWrapper_MessageType()
}

type MessageWrapper_EndpointRequest struct {
	EndpointRequest *EndpointRequest `protobuf:"bytes,1,opt,name=endpoint_request,json=endpointRequest,proto3,oneof"`
}

type MessageWrapper_EndpointResponse struct {
	EndpointResponse *EndpointResponse `protobuf:"bytes,2,opt,name=endpoint_response,json=endpointResponse,proto3,oneof"`
}

type MessageWrapper_ToRelay struct {
	ToRelay *ToRelayMessage `protobuf:"bytes,3,opt,name=to_relay,json=toRelay,proto3,oneof"`
}

type MessageWrapper_FromRelay struct {
	FromRelay *FromRelayMessage `protobuf:"bytes,4,opt,name=from_relay,json=fromRelay,proto3,oneof"`
}

type MessageWrapper_PingMessage struct {
	PingMessage *PingMessage `protobuf:"bytes,5,opt,name=ping_message,json=pingMessage,proto3,oneof"`
}

type MessageWrapper_PongMessage struct {
	PongMessage *PongMessage `protobuf:"bytes,6,opt,name=pong_message,json=pongMessage,proto3,oneof"`
}

func (*MessageWrapper_EndpointRequest) isMessageWrapper_MessageType() {}

func (*MessageWrapper_EndpointResponse) isMessageWrapper_MessageType() {}

func (*MessageWrapper_ToRelay) isMessageWrapper_MessageType() {}

func (*MessageWrapper_FromRelay) isMessageWrapper_MessageType() {}

func (*MessageWrapper_PingMessage) isMessageWrapper_MessageType() {}

func (*MessageWrapper_PongMessage) isMessageWrapper_MessageType() {}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            []byte                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"` // uint32 to match Go's uint16, protobuf doesn't have uint16
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_securemsg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_securemsg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_securemsg_proto_rawDescGZIP(), []int{1}
}

func (x *Address) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *Address) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type EndpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointRequest) Reset() {
	*x = EndpointRequest{}
	mi := &file_securemsg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointRequest) ProtoMessage() {}

func (x *EndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_securemsg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointRequest.ProtoReflect.Descriptor instead.
func (*EndpointRequest) Descriptor() ([]byte, []int) {
	return file_securemsg_proto_rawDescGZIP(), []int{2}
}

func (x *EndpointRequest) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type EndpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Addresses     []*Address             `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointResponse) Reset() {
	*x = EndpointResponse{}
	mi := &file_securemsg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointResponse) ProtoMessage() {}

func (x *EndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_securemsg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointResponse.ProtoReflect.Descriptor instead.
func (*EndpointResponse) Descriptor() ([]byte, []int) {
	return file_securemsg_proto_rawDescGZIP(), []int{3}
}

func (x *EndpointResponse) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *EndpointResponse) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type ToRelayMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DstKey        []byte                 `protobuf:"bytes,1,opt,name=dst_key,json=dstKey,proto3" json:"dst_key,omitempty"`
	SrcKey        []byte                 `protobuf:"bytes,2,opt,name=src_key,json=srcKey,proto3" json:"src_key,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToRelayMessage) Reset() {
	*x = ToRelayMessage{}
	mi := &file_securemsg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToRelayMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToRelayMessage) ProtoMessage() {}

func (x *ToRelayMessage) ProtoReflect() protoreflect.Message {
	mi := &file_securemsg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToRelayMessage.ProtoReflect.Descriptor instead.
func (*ToRelayMessage) Descriptor() ([]byte, []int) {
	return file_securemsg_proto_rawDescGZIP(), []int{4}
}

func (x *ToRelayMessage) GetDstKey() []byte {
	if x != nil {
		return x.DstKey
	}
	return nil
}

func (x *ToRelayMessage) GetSrcKey() []byte {
	if x != nil {
		return x.SrcKey
	}
	return nil
}

func (x *ToRelayMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type FromRelayMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DstKey        []byte                 `protobuf:"bytes,1,opt,name=dst_key,json=dstKey,proto3" json:"dst_key,omitempty"`
	SrcKey        []byte                 `protobuf:"bytes,2,opt,name=src_key,json=srcKey,proto3" json:"src_key,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FromRelayMessage) Reset() {
	*x = FromRelayMessage{}
	mi := &file_securemsg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FromRelayMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FromRelayMessage) ProtoMessage() {}

func (x *FromRelayMessage) ProtoReflect() protoreflect.Message {
	mi := &file_securemsg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FromRelayMessage.ProtoReflect.Descriptor instead.
func (*FromRelayMessage) Descriptor() ([]byte, []int) {
	return file_securemsg_proto_rawDescGZIP(), []int{5}
}

func (x *FromRelayMessage) GetDstKey() []byte {
	if x != nil {
		return x.DstKey
	}
	return nil
}

func (x *FromRelayMessage) GetSrcKey() []byte {
	if x != nil {
		return x.SrcKey
	}
	return nil
}

func (x *FromRelayMessage) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PingMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         uint32                 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"` // 4-byte nonce
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingMessage) Reset() {
	*x = PingMessage{}
	mi := &file_securemsg_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingMessage) ProtoMessage() {}

func (x *PingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_securemsg_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingMessage.ProtoReflect.Descriptor instead.
func (*PingMessage) Descriptor() ([]byte, []int) {
	return file_securemsg_proto_rawDescGZIP(), []int{6}
}

func (x *PingMessage) GetNonce() uint32 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type PongMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         uint32                 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"` // 4-byte nonce
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PongMessage) Reset() {
	*x = PongMessage{}
	mi := &file_securemsg_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongMessage) ProtoMessage() {}

func (x *PongMessage) ProtoReflect() protoreflect.Message {
	mi := &file_securemsg_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongMessage.ProtoReflect.Descriptor instead.
func (*PongMessage) Descriptor() ([]byte, []int) {
	return file_securemsg_proto_rawDescGZIP(), []int{7}
}

func (x *PongMessage) GetNonce() uint32 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

var File_securemsg_proto protoreflect.FileDescriptor

const file_securemsg_proto_rawDesc = "" +
	"\n" +
	"\x0fsecuremsg.proto\x12\tsecuremsg\"\xa5\x03\n" +
	"\x0eMessageWrapper\x12G\n" +
	"\x10endpoint_request\x18\x01 \x01(\v2\x1a.securemsg.EndpointRequestH\x00R\x0fendpointRequest\x12J\n" +
	"\x11endpoint_response\x18\x02 \x01(\v2\x1b.securemsg.EndpointResponseH\x00R\x10endpointResponse\x126\n" +
	"\bto_relay\x18\x03 \x01(\v2\x19.securemsg.ToRelayMessageH\x00R\atoRelay\x12<\n" +
	"\n" +
	"from_relay\x18\x04 \x01(\v2\x1b.securemsg.FromRelayMessageH\x00R\tfromRelay\x12;\n" +
	"\fping_message\x18\x05 \x01(\v2\x16.securemsg.PingMessageH\x00R\vpingMessage\x12;\n" +
	"\fpong_message\x18\x06 \x01(\v2\x16.securemsg.PongMessageH\x00R\vpongMessageB\x0e\n" +
	"\fmessage_type\"-\n" +
	"\aAddress\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\fR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\"0\n" +
	"\x0fEndpointRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\"c\n" +
	"\x10EndpointResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\x120\n" +
	"\taddresses\x18\x02 \x03(\v2\x12.securemsg.AddressR\taddresses\"V\n" +
	"\x0eToRelayMessage\x12\x17\n" +
	"\adst_key\x18\x01 \x01(\fR\x06dstKey\x12\x17\n" +
	"\asrc_key\x18\x02 \x01(\fR\x06srcKey\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"X\n" +
	"\x10FromRelayMessage\x12\x17\n" +
	"\adst_key\x18\x01 \x01(\fR\x06dstKey\x12\x17\n" +
	"\asrc_key\x18\x02 \x01(\fR\x06srcKey\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\"#\n" +
	"\vPingMessage\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\rR\x05nonce\"#\n" +
	"\vPongMessage\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\rR\x05nonceB+Z)github.com/bajacc/tinescale/pkg/securemsgb\x06proto3"

var (
	file_securemsg_proto_rawDescOnce sync.Once
	file_securemsg_proto_rawDescData []byte
)

func file_securemsg_proto_rawDescGZIP() []byte {
	file_securemsg_proto_rawDescOnce.Do(func() {
		file_securemsg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_securemsg_proto_rawDesc), len(file_securemsg_proto_rawDesc)))
	})
	return file_securemsg_proto_rawDescData
}

var file_securemsg_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_securemsg_proto_goTypes = []any{
	(*MessageWrapper)(nil),   // 0: securemsg.MessageWrapper
	(*Address)(nil),          // 1: securemsg.Address
	(*EndpointRequest)(nil),  // 2: securemsg.EndpointRequest
	(*EndpointResponse)(nil), // 3: securemsg.EndpointResponse
	(*ToRelayMessage)(nil),   // 4: securemsg.ToRelayMessage
	(*FromRelayMessage)(nil), // 5: securemsg.FromRelayMessage
	(*PingMessage)(nil),      // 6: securemsg.PingMessage
	(*PongMessage)(nil),      // 7: securemsg.PongMessage
}
var file_securemsg_proto_depIdxs = []int32{
	2, // 0: securemsg.MessageWrapper.endpoint_request:type_name -> securemsg.EndpointRequest
	3, // 1: securemsg.MessageWrapper.endpoint_response:type_name -> securemsg.EndpointResponse
	4, // 2: securemsg.MessageWrapper.to_relay:type_name -> securemsg.ToRelayMessage
	5, // 3: securemsg.MessageWrapper.from_relay:type_name -> securemsg.FromRelayMessage
	6, // 4: securemsg.MessageWrapper.ping_message:type_name -> securemsg.PingMessage
	7, // 5: securemsg.MessageWrapper.pong_message:type_name -> securemsg.PongMessage
	1, // 6: securemsg.EndpointResponse.addresses:type_name -> securemsg.Address
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_securemsg_proto_init() }
func file_securemsg_proto_init() {
	if File_securemsg_proto != nil {
		return
	}
	file_securemsg_proto_msgTypes[0].OneofWrappers = []any{
		(*MessageWrapper_EndpointRequest)(nil),
		(*MessageWrapper_EndpointResponse)(nil),
		(*MessageWrapper_ToRelay)(nil),
		(*MessageWrapper_FromRelay)(nil),
		(*MessageWrapper_PingMessage)(nil),
		(*MessageWrapper_PongMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_securemsg_proto_rawDesc), len(file_securemsg_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_securemsg_proto_goTypes,
		DependencyIndexes: file_securemsg_proto_depIdxs,
		MessageInfos:      file_securemsg_proto_msgTypes,
	}.Build()
	File_securemsg_proto = out.File
	file_securemsg_proto_goTypes = nil
	file_securemsg_proto_depIdxs = nil
}
