// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: pkg/proto/device.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LookupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"` // The peer's virtual IP (e.g. 10.0.0.2)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupRequest) Reset() {
	*x = LookupRequest{}
	mi := &file_pkg_proto_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupRequest) ProtoMessage() {}

func (x *LookupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupRequest.ProtoReflect.Descriptor instead.
func (*LookupRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_device_proto_rawDescGZIP(), []int{0}
}

func (x *LookupRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type LookupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Candidates    []string               `protobuf:"bytes,1,rep,name=candidates,proto3" json:"candidates,omitempty"` // List of "ip:port" strings
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupResponse) Reset() {
	*x = LookupResponse{}
	mi := &file_pkg_proto_device_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupResponse) ProtoMessage() {}

func (x *LookupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_device_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupResponse.ProtoReflect.Descriptor instead.
func (*LookupResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_device_proto_rawDescGZIP(), []int{1}
}

func (x *LookupResponse) GetCandidates() []string {
	if x != nil {
		return x.Candidates
	}
	return nil
}

var File_pkg_proto_device_proto protoreflect.FileDescriptor

const file_pkg_proto_device_proto_rawDesc = "" +
	"\n" +
	"\x16pkg/proto/device.proto\"\x1f\n" +
	"\rLookupRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\"0\n" +
	"\x0eLookupResponse\x12\x1e\n" +
	"\n" +
	"candidates\x18\x01 \x03(\tR\n" +
	"candidates2D\n" +
	"\rDeviceService\x123\n" +
	"\x10LookupCandidates\x12\x0e.LookupRequest\x1a\x0f.LookupResponseB\x11Z\x0fpkg/proto;protob\x06proto3"

var (
	file_pkg_proto_device_proto_rawDescOnce sync.Once
	file_pkg_proto_device_proto_rawDescData []byte
)

func file_pkg_proto_device_proto_rawDescGZIP() []byte {
	file_pkg_proto_device_proto_rawDescOnce.Do(func() {
		file_pkg_proto_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_device_proto_rawDesc), len(file_pkg_proto_device_proto_rawDesc)))
	})
	return file_pkg_proto_device_proto_rawDescData
}

var file_pkg_proto_device_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_device_proto_goTypes = []any{
	(*LookupRequest)(nil),  // 0: LookupRequest
	(*LookupResponse)(nil), // 1: LookupResponse
}
var file_pkg_proto_device_proto_depIdxs = []int32{
	0, // 0: DeviceService.LookupCandidates:input_type -> LookupRequest
	1, // 1: DeviceService.LookupCandidates:output_type -> LookupResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_device_proto_init() }
func file_pkg_proto_device_proto_init() {
	if File_pkg_proto_device_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_device_proto_rawDesc), len(file_pkg_proto_device_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_device_proto_goTypes,
		DependencyIndexes: file_pkg_proto_device_proto_depIdxs,
		MessageInfos:      file_pkg_proto_device_proto_msgTypes,
	}.Build()
	File_pkg_proto_device_proto = out.File
	file_pkg_proto_device_proto_goTypes = nil
	file_pkg_proto_device_proto_depIdxs = nil
}
