// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: endpointpool.proto

package endpointpool

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageWrapper struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to MessageType:
	//
	//	*MessageWrapper_EndpointRequest
	//	*MessageWrapper_EndpointResponse
	MessageType   isMessageWrapper_MessageType `protobuf_oneof:"message_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageWrapper) Reset() {
	*x = MessageWrapper{}
	mi := &file_endpointpool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageWrapper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageWrapper) ProtoMessage() {}

func (x *MessageWrapper) ProtoReflect() protoreflect.Message {
	mi := &file_endpointpool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageWrapper.ProtoReflect.Descriptor instead.
func (*MessageWrapper) Descriptor() ([]byte, []int) {
	return file_endpointpool_proto_rawDescGZIP(), []int{0}
}

func (x *MessageWrapper) GetMessageType() isMessageWrapper_MessageType {
	if x != nil {
		return x.MessageType
	}
	return nil
}

func (x *MessageWrapper) GetEndpointRequest() *EndpointRequest {
	if x != nil {
		if x, ok := x.MessageType.(*MessageWrapper_EndpointRequest); ok {
			return x.EndpointRequest
		}
	}
	return nil
}

func (x *MessageWrapper) GetEndpointResponse() *EndpointResponse {
	if x != nil {
		if x, ok := x.MessageType.(*MessageWrapper_EndpointResponse); ok {
			return x.EndpointResponse
		}
	}
	return nil
}

type isMessageWrapper_MessageType interface {
	isMessageWrapper_MessageType()
}

type MessageWrapper_EndpointRequest struct {
	EndpointRequest *EndpointRequest `protobuf:"bytes,1,opt,name=endpoint_request,json=endpointRequest,proto3,oneof"`
}

type MessageWrapper_EndpointResponse struct {
	EndpointResponse *EndpointResponse `protobuf:"bytes,2,opt,name=endpoint_response,json=endpointResponse,proto3,oneof"`
}

func (*MessageWrapper_EndpointRequest) isMessageWrapper_MessageType() {}

func (*MessageWrapper_EndpointResponse) isMessageWrapper_MessageType() {}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            []byte                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"` // uint32 to match Go's uint16, protobuf doesn't have uint16
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_endpointpool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_endpointpool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_endpointpool_proto_rawDescGZIP(), []int{1}
}

func (x *Address) GetIp() []byte {
	if x != nil {
		return x.Ip
	}
	return nil
}

func (x *Address) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

type EndpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointRequest) Reset() {
	*x = EndpointRequest{}
	mi := &file_endpointpool_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointRequest) ProtoMessage() {}

func (x *EndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_endpointpool_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointRequest.ProtoReflect.Descriptor instead.
func (*EndpointRequest) Descriptor() ([]byte, []int) {
	return file_endpointpool_proto_rawDescGZIP(), []int{2}
}

func (x *EndpointRequest) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

type EndpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     uint32                 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Addresses     []*Address             `protobuf:"bytes,2,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointResponse) Reset() {
	*x = EndpointResponse{}
	mi := &file_endpointpool_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointResponse) ProtoMessage() {}

func (x *EndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_endpointpool_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointResponse.ProtoReflect.Descriptor instead.
func (*EndpointResponse) Descriptor() ([]byte, []int) {
	return file_endpointpool_proto_rawDescGZIP(), []int{3}
}

func (x *EndpointResponse) GetRequestId() uint32 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *EndpointResponse) GetAddresses() []*Address {
	if x != nil {
		return x.Addresses
	}
	return nil
}

var File_endpointpool_proto protoreflect.FileDescriptor

const file_endpointpool_proto_rawDesc = "" +
	"\n" +
	"\x12endpointpool.proto\x12\fendpointpool\"\xbb\x01\n" +
	"\x0eMessageWrapper\x12J\n" +
	"\x10endpoint_request\x18\x01 \x01(\v2\x1d.endpointpool.EndpointRequestH\x00R\x0fendpointRequest\x12M\n" +
	"\x11endpoint_response\x18\x02 \x01(\v2\x1e.endpointpool.EndpointResponseH\x00R\x10endpointResponseB\x0e\n" +
	"\fmessage_type\"-\n" +
	"\aAddress\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\fR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\"0\n" +
	"\x0fEndpointRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\"f\n" +
	"\x10EndpointResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\rR\trequestId\x123\n" +
	"\taddresses\x18\x02 \x03(\v2\x15.endpointpool.AddressR\taddressesB.Z,github.com/bajacc/tinescale/pkg/endpointpoolb\x06proto3"

var (
	file_endpointpool_proto_rawDescOnce sync.Once
	file_endpointpool_proto_rawDescData []byte
)

func file_endpointpool_proto_rawDescGZIP() []byte {
	file_endpointpool_proto_rawDescOnce.Do(func() {
		file_endpointpool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_endpointpool_proto_rawDesc), len(file_endpointpool_proto_rawDesc)))
	})
	return file_endpointpool_proto_rawDescData
}

var file_endpointpool_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_endpointpool_proto_goTypes = []any{
	(*MessageWrapper)(nil),   // 0: endpointpool.MessageWrapper
	(*Address)(nil),          // 1: endpointpool.Address
	(*EndpointRequest)(nil),  // 2: endpointpool.EndpointRequest
	(*EndpointResponse)(nil), // 3: endpointpool.EndpointResponse
}
var file_endpointpool_proto_depIdxs = []int32{
	2, // 0: endpointpool.MessageWrapper.endpoint_request:type_name -> endpointpool.EndpointRequest
	3, // 1: endpointpool.MessageWrapper.endpoint_response:type_name -> endpointpool.EndpointResponse
	1, // 2: endpointpool.EndpointResponse.addresses:type_name -> endpointpool.Address
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_endpointpool_proto_init() }
func file_endpointpool_proto_init() {
	if File_endpointpool_proto != nil {
		return
	}
	file_endpointpool_proto_msgTypes[0].OneofWrappers = []any{
		(*MessageWrapper_EndpointRequest)(nil),
		(*MessageWrapper_EndpointResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_endpointpool_proto_rawDesc), len(file_endpointpool_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_endpointpool_proto_goTypes,
		DependencyIndexes: file_endpointpool_proto_depIdxs,
		MessageInfos:      file_endpointpool_proto_msgTypes,
	}.Build()
	File_endpointpool_proto = out.File
	file_endpointpool_proto_goTypes = nil
	file_endpointpool_proto_depIdxs = nil
}
